name: 'PHP Coding Standard'
description: 'PHP Coding Standard'
inputs:
  php-version:
    description: 'PHP Version'
    required: true
    default: '7.4'
  extensions:
    description: 'Extensions PHP'
    required: true
    default: 'bcmath, iconv, ctype, gd, mbstring, mysqli, pdo, pdo_mysql, sockets, zip, soap, intl, fileinfo, json, libxml, openssl, pcntl, posix, simplexml, zend-opcache, runkit7, igbinary, redis'
  tools:
    description: 'Tools'
    required: true
    default: 'cs2pr'
  
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.extensions }}
        tools: ${{ inputs.tools }}

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader
    
    - name: Run PHP_CodeSniffer
      run: vendor/bin/phpcs -p src/ tests/ --report=checkstyle -q | cs2pr

    - name: Run PHP Mess Detector
      run: vendor/bin/phpmd src/,tests/ github phpmd-ruleset.xml

    - name: Run PHPStan
      run: vendor/bin/phpstan --configuration=phpstan.neon analyse --error-format=checkstyle --no-progress | cs2pr
      