name: 'PHP Coding Standard'
description: 'PHP Coding Standard'
inputs:
  php-version:
    description: 'PHP Version'
    required: true
    default: '7.4'
  extensions:
    description: 'Extensions PHP'
    required: true
    default: 'bcmath, iconv, ctype, gd, mbstring, mysqli, pdo, pdo_mysql, sockets, zip, soap, intl, fileinfo, json, libxml, openssl, pcntl, posix, simplexml, zend-opcache, runkit7, igbinary, redis'
  tools:
    description: 'Tools'
    required: true
    default: 'cs2pr'
outputs:
  install-dependencies:
    description: "Install Dependencies"
    value: ${{ steps.install-dependencies }}
  run-php-code-sniffer:
    description: "Run PHP CodeSniffer"
    value: ${{ steps.run-php-code-sniffer }}
  run-php-mess-detector:
    description: "Run PHP MessDetector"
    value: ${{ steps.run-php-mess-detector }}
  run-php-stan:
    description: "Run PHP Stan"
    value: ${{ steps.run-php-stan }}
  
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.extensions }}
        tools: ${{ inputs.tools }}

    - id: install-dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader
      shell: bash
    
    - id: run-php-code-sniffer
      run: vendor/bin/phpcs -p src/ tests/ --report=checkstyle -q | cs2pr
      shell: bash

    - id: run-php-mess-detector
      run: vendor/bin/phpmd src/,tests/ github phpmd-ruleset.xml
      shell: bash

    - id: run-php-stan
      run: vendor/bin/phpstan --configuration=phpstan.neon analyse --error-format=checkstyle --no-progress | cs2pr
      shell: bash
      